# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='排序'),
        ),
    ]
